version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nalib-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - nalib-db-data:/var/lib/postgresql/data
    networks:
      - nalib-net

  web:
    build: .
    container_name: nalib-web
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      BACKUP_DIR: ${BACKUP_DIR}   # Ensure this line is present!
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ACCESS_TOKEN_EXPIRES: ${JWT_ACCESS_TOKEN_EXPIRES}
      JWT_REFRESH_TOKEN_EXPIRES: ${JWT_REFRESH_TOKEN_EXPIRES}
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - nalib-net

networks:
  nalib-net:
    driver: bridge

volumes:
  nalib-db-data:
